// Optional site-wide ambience. Put the file in assets/audio and add its path.
// Playback begins only after the visitor selects “Sound on”.
export const globalAudio = {
  src: "",
  label: "Ambient soundscape",
  volume: 0.35,
};

export const species = [
  // Media paths are optional. Put files in assets/audio or assets/video, then
  // replace an empty string below with e.g. "./assets/video/great-auk-habitat.mp4".
  // Hero portraits accept landscape or portrait images. Use portraitFit "cover"
  // to fill the frame or "contain" to show the complete image. Adjust the focal
  // point with portraitPosition, e.g. "center center", "25% center", or "right top".
  {
    id: "great-auk",
    storyId: "great-auk",
    index: "01",
    year: 1844,
    name: "Great Auk",
    individualName: "The final pair",
    scientificName: "Pinguinus impennis",
    location: "Eldey Island · North Atlantic",
    summary:
      "On a remote Icelandic island, the last known breeding pair were killed beside their single egg—ending centuries of life across the North Atlantic.",
    detail:
      "The Great Auk once gathered in immense colonies across the North Atlantic. Flightless and unafraid of people, it was taken for meat, feathers, oil and specimens until only a final pair remained on Eldey Island.",
    cause: "Hunting, egg collecting and commercial exploitation",
    accent: "#9aa58e",
    habitatLabel: "North Atlantic cliffs · habitat image placeholder",
    portraitLabel: "Great Auk · species portrait placeholder",
    portraitImage: "/assets/images/greatauk.jpg",
    portraitFit: "contain",
    portraitPosition: "30% center",
    archiveLabel: "Historical illustration · archive placeholder",
    habitatVideo: "assets/video/greatAukHabitat1.mp4",
    audioSrc: "",
    videoSrc: "",
    sourceLabel: "Source and image credit to be added",

  },
  {
    id: "passenger-pigeon",
    storyId: "passenger-pigeon",
    index: "02",
    year: 1914,
    name: "Passenger Pigeon",
    individualName: "Martha",
    scientificName: "Ectopistes migratorius",
    location: "Cincinnati · United States",
    summary:
      "A bird once counted in billions ended with Martha, alone at Cincinnati Zoo, after industrial hunting and forest loss dismantled its enormous flocks.",
    detail:
      "Passenger Pigeon flocks once darkened North American skies for hours. Industrial hunting and forest loss collapsed the vast social populations on which the species depended. Martha died at Cincinnati Zoo in 1914.",
    cause: "Commercial hunting and habitat loss",
    accent: "#a79582",
    habitatLabel: "North American forest · habitat image placeholder",
    portraitLabel: "Martha · individual portrait placeholder",
    portraitImage: "assets/images/Martha_last_passenger_pigeon_1912.jpg",
    portraitFit: "cover",
    portraitPosition: "center center",
    archiveLabel: "Passenger pigeon flock · archive placeholder",
    habitatVideo: "assets/video/passengerPigeonHabitat.mp4",
    audioSrc: "",
    videoSrc: "",
    sourceLabel: "Source and image credit to be added",
  },
  {
    id: "thylacine",
    storyId: "thylacine",
    index: "03",
    year: 1936,
    name: "Thylacine",
    individualName: "Benjamin",
    scientificName: "Thylacinus cynocephalus",
    location: "Hobart · Tasmania",
    summary:
      "Hunted as a threat to livestock, the Thylacine received legal protection only weeks before the last known captive animal died in Hobart.",
    detail:
      "Persecution encouraged by a government bounty intensified the decline of Tasmania's largest marsupial predator. The final known captive animal died at Beaumaris Zoo, only weeks after legal protection began.",
    cause: "Bounty hunting, persecution and ecological pressure",
    accent: "#ae8c63",
    habitatLabel: "Tasmanian bushland · habitat image placeholder",
    portraitLabel: "Benjamin · individual portrait placeholder",
    portraitImage: "assets/images/thylacine_historical_illustration_01.jpg",
    portraitFit: "contain",
    portraitPosition: "center center",
    archiveLabel: "Beaumaris Zoo film · video placeholder",
    habitatVideo: "assets/video/ThylacineHabitatHatbitat.mp4",
    audioSrc: "",
    videoSrc: "",
    sourceLabel: "Source and footage credit to be added",
  },
  {
    id: "kauai-oo",
    storyId: "kauai-oo",
    index: "04",
    year: 1987,
    name: "Kauaʻi ʻōʻō",
    individualName: "The last voice",
    scientificName: "Moho braccatus",
    location: "Alakaʻi Swamp · Kauaʻi",
    summary:
      "In Kauaʻi’s rain-soaked forest, a lone bird called for a mate. No answer came, but the recording of its voice remains.",
    detail:
      "The final confirmed recording captures a lone male calling for a mate. Habitat loss, invasive species, disease and severe storms had reduced the population until the forest held only one side of the duet.",
    cause: "Habitat loss, invasive species, disease and storms",
    accent: "#779183",
    habitatLabel: "Alakaʻi rainforest · habitat image placeholder",
    portraitLabel: "Kauaʻi ʻōʻō · species portrait placeholder",
    portraitImage: "assets/images/kauai_Oo_illustration_01.jpg",
    portraitFit: "contain",
    portraitPosition: "50% center",
    archiveLabel: "Last call · audio placeholder",
    habitatVideo: "assets/video/kauaiOoHabitat.mp4",
    audioSrc: "",
    videoSrc: "",
    sourceLabel: "Audio, source and image credit to be added",
  },
  {
    id: "baiji",
    storyId: "baiji",
    index: "05",
    year: 2006,
    name: "Baiji",
    individualName: "Qiqi",
    scientificName: "Lipotes vexillifer",
    location: "Yangtze River · China",
    summary:
      "Qiqi survived for decades in human care while the wild population disappeared. In 2006, a six-week Yangtze survey found no Baiji.",
    detail:
      "The Baiji evolved within the Yangtze for millions of years. Entanglement, vessel traffic, fishing pressure and river development transformed its habitat. The 2006 survey led researchers to declare it functionally extinct.",
    cause: "Bycatch, vessel traffic, fishing and river development",
    accent: "#728e94",
    habitatLabel: "Yangtze River · habitat image placeholder",
    portraitLabel: "Qiqi · individual portrait placeholder",
    portraitImage: "assets/images/baiji_illustration_03.jpg",
    portraitFit: "contain",
    portraitPosition: "center center",
    archiveLabel: "Yangtze survey · archive placeholder",
    habitatVideo: "assets/video/BaijiHabitat.mp4",
    audioSrc: "",
    videoSrc: "",
    sourceLabel: "Source and image credit to be added",
  },
  {
    id: "lonesome-george",
    storyId: "pinta-tortoise",
    index: "06",
    year: 2012,
    name: "Lonesome George",
    individualName: "Lonesome George",
    scientificName: "Chelonoidis abingdonii",
    location: "Pinta Island · Galápagos",
    summary:
      "For forty years, Lonesome George lived as the last known Pinta tortoise—a visible reminder that protecting one individual cannot restore a vanished population.",
    detail:
      "Introduced goats devastated Pinta Island vegetation after earlier exploitation had reduced its tortoises. George became a global conservation symbol, but breeding attempts produced no surviving offspring.",
    cause: "Historic exploitation and introduced goats",
    accent: "#9b8c67",
    habitatLabel: "Pinta Island · habitat image placeholder",
    portraitLabel: "Lonesome George · individual portrait placeholder",
    portraitImage: "assets/images/george_illustartion.jpg",
    portraitFit: "contain",
    portraitPosition: "center center",
    archiveLabel: "Pinta habitat change · archive placeholder",
    habitatVideo: "assets/video/PintaHabitat.mp4",
    audioSrc: "",
    videoSrc: "",
    sourceLabel: "Source and image credit to be added",
  },
];

export const recentExtinctions = [
  {
    id: "bramble-cay-melomys",
    year: 2015,
    name: "Bramble Cay Melomys",
    status: "Provisional timeline entry — verify before publication",
  },
  {
    id: "christmas-island-pipistrelle",
    year: 2017,
    name: "Christmas Island Pipistrelle",
    status: "Provisional timeline entry — verify before publication",
  },
  {
    id: "northern-white-rhinoceros",
    year: 2018,
    name: "Northern White Rhinoceros",
    status: "Functional-extinction placeholder — verify wording",
  },
  {
    id: "chinese-paddlefish",
    year: 2020,
    name: "Chinese Paddlefish",
    status: "Provisional timeline entry — verify before publication",
  },
  {
    id: "slender-billed-curlew",
    year: 2025,
    name: "Slender-billed Curlew",
    status: "Proposal placeholder — status and year require verification",
  },
];
