export const species = [
  {
    id: "great-auk",
    index: "01",
    year: 1844,
    name: "Great Auk",
    individualName: "The final pair",
    scientificName: "Pinguinus impennis",
    location: "Eldey Island · North Atlantic",
    summary:
      "On a low black island off Iceland, the final known breeding pair were killed within minutes of one another.",
    detail:
      "The Great Auk once gathered in immense colonies across the North Atlantic. Flightless and unafraid of people, it was taken for meat, feathers, oil and specimens until only a final pair remained on Eldey Island.",
    cause: "Hunting, egg collecting and commercial exploitation",
    accent: "#9aa58e",
    habitatLabel: "North Atlantic cliffs · habitat image placeholder",
    portraitLabel: "Great Auk · species portrait placeholder",
    archiveLabel: "Historical illustration · archive placeholder",
    sourceLabel: "Source and image credit to be added",
  },
  {
    id: "passenger-pigeon",
    index: "02",
    year: 1914,
    name: "Passenger Pigeon",
    individualName: "Martha",
    scientificName: "Ectopistes migratorius",
    location: "Cincinnati · United States",
    summary:
      "A bird once counted in billions ended with one individual, Martha, alone in a zoo enclosure.",
    detail:
      "Passenger Pigeon flocks once darkened North American skies for hours. Industrial hunting and forest loss collapsed the vast social populations on which the species depended. Martha died at Cincinnati Zoo in 1914.",
    cause: "Commercial hunting and habitat loss",
    accent: "#a79582",
    habitatLabel: "North American forest · habitat image placeholder",
    portraitLabel: "Martha · individual portrait placeholder",
    archiveLabel: "Passenger pigeon flock · archive placeholder",
    sourceLabel: "Source and image credit to be added",
  },
  {
    id: "thylacine",
    index: "03",
    year: 1936,
    name: "Thylacine",
    individualName: "Benjamin",
    scientificName: "Thylacinus cynocephalus",
    location: "Hobart · Tasmania",
    summary:
      "The last known captive thylacine paced behind wire while a species disappeared beyond the frame.",
    detail:
      "Persecution encouraged by a government bounty intensified the decline of Tasmania's largest marsupial predator. The final known captive animal died at Beaumaris Zoo, only weeks after legal protection began.",
    cause: "Bounty hunting, persecution and ecological pressure",
    accent: "#ae8c63",
    habitatLabel: "Tasmanian bushland · habitat image placeholder",
    portraitLabel: "Benjamin · individual portrait placeholder",
    archiveLabel: "Beaumaris Zoo film · video placeholder",
    sourceLabel: "Source and footage credit to be added",
  },
  {
    id: "kauai-oo",
    index: "04",
    year: 1987,
    name: "Kauaʻi ʻōʻō",
    individualName: "The last voice",
    scientificName: "Moho braccatus",
    location: "Alakaʻi Swamp · Kauaʻi",
    summary:
      "A male bird called into the rainforest. The answering voice never came.",
    detail:
      "The final confirmed recording captures a lone male calling for a mate. Habitat loss, invasive species, disease and severe storms had reduced the population until the forest held only one side of the duet.",
    cause: "Habitat loss, invasive species, disease and storms",
    accent: "#779183",
    habitatLabel: "Alakaʻi rainforest · habitat image placeholder",
    portraitLabel: "Kauaʻi ʻōʻō · species portrait placeholder",
    archiveLabel: "Last call · audio placeholder",
    sourceLabel: "Audio, source and image credit to be added",
  },
  {
    id: "baiji",
    index: "05",
    year: 2006,
    name: "Baiji",
    individualName: "Qiqi",
    scientificName: "Lipotes vexillifer",
    location: "Yangtze River · China",
    summary:
      "A six-week survey crossed the Yangtze and returned without a single confirmed sighting.",
    detail:
      "The Baiji evolved within the Yangtze for millions of years. Entanglement, vessel traffic, fishing pressure and river development transformed its habitat. The 2006 survey led researchers to declare it functionally extinct.",
    cause: "Bycatch, vessel traffic, fishing and river development",
    accent: "#728e94",
    habitatLabel: "Yangtze River · habitat image placeholder",
    portraitLabel: "Qiqi · individual portrait placeholder",
    archiveLabel: "Yangtze survey · archive placeholder",
    sourceLabel: "Source and image credit to be added",
  },
  {
    id: "lonesome-george",
    index: "06",
    year: 2012,
    name: "Lonesome George",
    individualName: "Lonesome George",
    scientificName: "Chelonoidis abingdonii",
    location: "Pinta Island · Galápagos",
    summary:
      "For decades, George carried the visible weight of being the last known member of his kind.",
    detail:
      "Introduced goats devastated Pinta Island vegetation after earlier exploitation had reduced its tortoises. George became a global conservation symbol, but breeding attempts produced no surviving offspring.",
    cause: "Historic exploitation and introduced goats",
    accent: "#9b8c67",
    habitatLabel: "Pinta Island · habitat image placeholder",
    portraitLabel: "Lonesome George · individual portrait placeholder",
    archiveLabel: "Pinta habitat change · archive placeholder",
    sourceLabel: "Source and image credit to be added",
  },
];

export const recentExtinctions = [
  {
    id: "bramble-cay-melomys",
    year: 2015,
    name: "Bramble Cay Melomys",
    status: "Provisional timeline entry — verify before publication",
  },
  {
    id: "christmas-island-pipistrelle",
    year: 2017,
    name: "Christmas Island Pipistrelle",
    status: "Provisional timeline entry — verify before publication",
  },
  {
    id: "northern-white-rhinoceros",
    year: 2018,
    name: "Northern White Rhinoceros",
    status: "Functional-extinction placeholder — verify wording",
  },
  {
    id: "chinese-paddlefish",
    year: 2020,
    name: "Chinese Paddlefish",
    status: "Provisional timeline entry — verify before publication",
  },
  {
    id: "slender-billed-curlew",
    year: 2025,
    name: "Slender-billed Curlew",
    status: "Proposal placeholder — status and year require verification",
  },
  {
    id: "unknown-next",
    year: 2026,
    name: "The next species",
    status: "Narrative placeholder",
  },
];
